INSERT INTO test.group_names (id, name, user_id) VALUES (1, 'все контакты', 1);
INSERT INTO test.group_names (id, name, user_id) VALUES (2, 'друзья', 1);
INSERT INTO test.group_names (id, name, user_id) VALUES (3, 'знакомые', 1);
INSERT INTO test.group_names (id, name, user_id) VALUES (4, 'клиенты', 1);
INSERT INTO test.group_names (id, name, user_id) VALUES (5, 'все контакты', 2);
INSERT INTO test.group_names (id, name, user_id) VALUES (6, 'друзья', 2);
INSERT INTO test.group_names (id, name, user_id) VALUES (7, 'знакомые', 2);
INSERT INTO test.group_names (id, name, user_id) VALUES (8, 'клиенты', 2);
INSERT INTO test.group_names (id, name, user_id) VALUES (9, 'все контакты', 3);
INSERT INTO test.group_names (id, name, user_id) VALUES (10, 'друзья', 3);
INSERT INTO test.group_names (id, name, user_id) VALUES (11, 'знакомые', 3);
INSERT INTO test.group_names (id, name, user_id) VALUES (12, 'клиенты', 3);
INSERT INTO test.group_names (id, name, user_id) VALUES (13, 'все контакты', 4);
INSERT INTO test.group_names (id, name, user_id) VALUES (14, 'друзья', 4);
INSERT INTO test.group_names (id, name, user_id) VALUES (15, 'знакомые', 4);
INSERT INTO test.group_names (id, name, user_id) VALUES (16, 'клиенты', 4);
INSERT INTO test.group_names (id, name, user_id) VALUES (17, 'все контакты', 5);
INSERT INTO test.group_names (id, name, user_id) VALUES (18, 'друзья', 5);
INSERT INTO test.group_names (id, name, user_id) VALUES (19, 'знакомые', 5);
INSERT INTO test.group_names (id, name, user_id) VALUES (20, 'клиенты', 5);
INSERT INTO test.group_names (id, name, user_id) VALUES (21, 'все контакты', 6);
INSERT INTO test.group_names (id, name, user_id) VALUES (22, 'друзья', 6);
INSERT INTO test.group_names (id, name, user_id) VALUES (23, 'знакомые', 6);
INSERT INTO test.group_names (id, name, user_id) VALUES (24, 'клиенты', 6);
INSERT INTO test.group_names (id, name, user_id) VALUES (25, 'все контакты', 7);
INSERT INTO test.group_names (id, name, user_id) VALUES (26, 'друзья', 7);
INSERT INTO test.group_names (id, name, user_id) VALUES (27, 'знакомые', 7);
INSERT INTO test.group_names (id, name, user_id) VALUES (28, 'клиенты', 7);
INSERT INTO test.group_names (id, name, user_id) VALUES (29, 'все контакты', 8);
INSERT INTO test.group_names (id, name, user_id) VALUES (30, 'друзья', 8);
INSERT INTO test.group_names (id, name, user_id) VALUES (31, 'знакомые', 8);
INSERT INTO test.group_names (id, name, user_id) VALUES (32, 'клиенты', 8);
INSERT INTO test.group_names (id, name, user_id) VALUES (33, 'все контакты', 9);
INSERT INTO test.group_names (id, name, user_id) VALUES (34, 'друзья', 9);
INSERT INTO test.group_names (id, name, user_id) VALUES (35, 'знакомые', 9);
INSERT INTO test.group_names (id, name, user_id) VALUES (36, 'клиенты', 9);
INSERT INTO test.group_names (id, name, user_id) VALUES (37, 'все контакты', 10);
INSERT INTO test.group_names (id, name, user_id) VALUES (38, 'друзья', 10);
INSERT INTO test.group_names (id, name, user_id) VALUES (39, 'знакомые', 10);
INSERT INTO test.group_names (id, name, user_id) VALUES (40, 'клиенты', 10);
INSERT INTO test.group_names (id, name, user_id) VALUES (41, 'все контакты', 11);
INSERT INTO test.group_names (id, name, user_id) VALUES (42, 'друзья', 11);
INSERT INTO test.group_names (id, name, user_id) VALUES (43, 'знакомые', 11);
INSERT INTO test.group_names (id, name, user_id) VALUES (44, 'клиенты', 11);
INSERT INTO test.group_names (id, name, user_id) VALUES (45, 'все контакты', 12);
INSERT INTO test.group_names (id, name, user_id) VALUES (46, 'друзья', 12);
INSERT INTO test.group_names (id, name, user_id) VALUES (47, 'знакомые', 12);
INSERT INTO test.group_names (id, name, user_id) VALUES (48, 'клиенты', 12);
INSERT INTO test.group_names (id, name, user_id) VALUES (49, 'все контакты', 13);
INSERT INTO test.group_names (id, name, user_id) VALUES (50, 'друзья', 13);
INSERT INTO test.group_names (id, name, user_id) VALUES (51, 'знакомые', 13);
INSERT INTO test.group_names (id, name, user_id) VALUES (52, 'клиенты', 13);
INSERT INTO test.group_names (id, name, user_id) VALUES (53, 'все контакты', 14);
INSERT INTO test.group_names (id, name, user_id) VALUES (54, 'друзья', 14);
INSERT INTO test.group_names (id, name, user_id) VALUES (55, 'знакомые', 14);
INSERT INTO test.group_names (id, name, user_id) VALUES (56, 'клиенты', 14);
INSERT INTO test.group_names (id, name, user_id) VALUES (57, 'все контакты', 15);
INSERT INTO test.group_names (id, name, user_id) VALUES (58, 'друзья', 15);
INSERT INTO test.group_names (id, name, user_id) VALUES (59, 'знакомые', 15);
INSERT INTO test.group_names (id, name, user_id) VALUES (60, 'клиенты', 15);
INSERT INTO test.group_names (id, name, user_id) VALUES (61, 'все контакты', 16);
INSERT INTO test.group_names (id, name, user_id) VALUES (62, 'друзья', 16);
INSERT INTO test.group_names (id, name, user_id) VALUES (63, 'знакомые', 16);
INSERT INTO test.group_names (id, name, user_id) VALUES (64, 'клиенты', 16);
INSERT INTO test.group_names (id, name, user_id) VALUES (65, 'все контакты', 17);
INSERT INTO test.group_names (id, name, user_id) VALUES (66, 'друзья', 17);
INSERT INTO test.group_names (id, name, user_id) VALUES (67, 'знакомые', 17);
INSERT INTO test.group_names (id, name, user_id) VALUES (68, 'клиенты', 17);
INSERT INTO test.group_names (id, name, user_id) VALUES (69, 'все контакты', 18);
INSERT INTO test.group_names (id, name, user_id) VALUES (70, 'друзья', 18);
INSERT INTO test.group_names (id, name, user_id) VALUES (71, 'знакомые', 18);
INSERT INTO test.group_names (id, name, user_id) VALUES (72, 'клиенты', 18);
INSERT INTO test.group_names (id, name, user_id) VALUES (73, 'все контакты', 19);
INSERT INTO test.group_names (id, name, user_id) VALUES (74, 'друзья', 19);
INSERT INTO test.group_names (id, name, user_id) VALUES (75, 'знакомые', 19);
INSERT INTO test.group_names (id, name, user_id) VALUES (76, 'клиенты', 19);
INSERT INTO test.group_names (id, name, user_id) VALUES (77, 'все контакты', 20);
INSERT INTO test.group_names (id, name, user_id) VALUES (78, 'друзья', 20);
INSERT INTO test.group_names (id, name, user_id) VALUES (79, 'знакомые', 20);
INSERT INTO test.group_names (id, name, user_id) VALUES (80, 'клиенты', 20);
INSERT INTO test.group_names (id, name, user_id) VALUES (81, 'все контакты', 21);
INSERT INTO test.group_names (id, name, user_id) VALUES (82, 'друзья', 21);
INSERT INTO test.group_names (id, name, user_id) VALUES (83, 'знакомые', 21);
INSERT INTO test.group_names (id, name, user_id) VALUES (84, 'клиенты', 21);
INSERT INTO test.group_names (id, name, user_id) VALUES (85, 'все контакты', 22);
INSERT INTO test.group_names (id, name, user_id) VALUES (86, 'друзья', 22);
INSERT INTO test.group_names (id, name, user_id) VALUES (87, 'знакомые', 22);
INSERT INTO test.group_names (id, name, user_id) VALUES (88, 'клиенты', 22);
INSERT INTO test.group_names (id, name, user_id) VALUES (89, 'все контакты', 23);
INSERT INTO test.group_names (id, name, user_id) VALUES (90, 'друзья', 23);
INSERT INTO test.group_names (id, name, user_id) VALUES (91, 'знакомые', 23);
INSERT INTO test.group_names (id, name, user_id) VALUES (92, 'клиенты', 23);
INSERT INTO test.group_names (id, name, user_id) VALUES (93, 'все контакты', 24);
INSERT INTO test.group_names (id, name, user_id) VALUES (94, 'друзья', 24);
INSERT INTO test.group_names (id, name, user_id) VALUES (95, 'знакомые', 24);
INSERT INTO test.group_names (id, name, user_id) VALUES (96, 'клиенты', 24);
INSERT INTO test.group_names (id, name, user_id) VALUES (97, 'все контакты', 25);
INSERT INTO test.group_names (id, name, user_id) VALUES (98, 'друзья', 25);
INSERT INTO test.group_names (id, name, user_id) VALUES (99, 'знакомые', 25);
INSERT INTO test.group_names (id, name, user_id) VALUES (100, 'клиенты', 25);
INSERT INTO test.group_names (id, name, user_id) VALUES (101, 'все контакты', 26);
INSERT INTO test.group_names (id, name, user_id) VALUES (102, 'друзья', 26);
INSERT INTO test.group_names (id, name, user_id) VALUES (103, 'знакомые', 26);
INSERT INTO test.group_names (id, name, user_id) VALUES (104, 'клиенты', 26);
INSERT INTO test.group_names (id, name, user_id) VALUES (105, 'все контакты', 27);
INSERT INTO test.group_names (id, name, user_id) VALUES (106, 'друзья', 27);
INSERT INTO test.group_names (id, name, user_id) VALUES (107, 'знакомые', 27);
INSERT INTO test.group_names (id, name, user_id) VALUES (108, 'клиенты', 27);
INSERT INTO test.group_names (id, name, user_id) VALUES (109, 'все контакты', 28);
INSERT INTO test.group_names (id, name, user_id) VALUES (110, 'друзья', 28);
INSERT INTO test.group_names (id, name, user_id) VALUES (111, 'знакомые', 28);
INSERT INTO test.group_names (id, name, user_id) VALUES (112, 'клиенты', 28);
INSERT INTO test.group_names (id, name, user_id) VALUES (113, 'все контакты', 29);
INSERT INTO test.group_names (id, name, user_id) VALUES (114, 'друзья', 29);
INSERT INTO test.group_names (id, name, user_id) VALUES (115, 'знакомые', 29);
INSERT INTO test.group_names (id, name, user_id) VALUES (116, 'клиенты', 29);
INSERT INTO test.group_names (id, name, user_id) VALUES (117, 'все контакты', 30);
INSERT INTO test.group_names (id, name, user_id) VALUES (118, 'друзья', 30);
INSERT INTO test.group_names (id, name, user_id) VALUES (119, 'знакомые', 30);
INSERT INTO test.group_names (id, name, user_id) VALUES (120, 'клиенты', 30);
INSERT INTO test.group_names (id, name, user_id) VALUES (121, 'все контакты', 31);
INSERT INTO test.group_names (id, name, user_id) VALUES (122, 'друзья', 31);
INSERT INTO test.group_names (id, name, user_id) VALUES (123, 'знакомые', 31);
INSERT INTO test.group_names (id, name, user_id) VALUES (124, 'клиенты', 31);
INSERT INTO test.group_names (id, name, user_id) VALUES (125, 'все контакты', 32);
INSERT INTO test.group_names (id, name, user_id) VALUES (126, 'друзья', 32);
INSERT INTO test.group_names (id, name, user_id) VALUES (127, 'знакомые', 32);
INSERT INTO test.group_names (id, name, user_id) VALUES (128, 'клиенты', 32);
INSERT INTO test.group_names (id, name, user_id) VALUES (129, 'все контакты', 33);
INSERT INTO test.group_names (id, name, user_id) VALUES (130, 'друзья', 33);
INSERT INTO test.group_names (id, name, user_id) VALUES (131, 'знакомые', 33);
INSERT INTO test.group_names (id, name, user_id) VALUES (132, 'клиенты', 33);
INSERT INTO test.group_names (id, name, user_id) VALUES (133, 'все контакты', 34);
INSERT INTO test.group_names (id, name, user_id) VALUES (134, 'друзья', 34);
INSERT INTO test.group_names (id, name, user_id) VALUES (135, 'знакомые', 34);
INSERT INTO test.group_names (id, name, user_id) VALUES (136, 'клиенты', 34);
INSERT INTO test.group_names (id, name, user_id) VALUES (137, 'все контакты', 35);
INSERT INTO test.group_names (id, name, user_id) VALUES (138, 'друзья', 35);
INSERT INTO test.group_names (id, name, user_id) VALUES (139, 'знакомые', 35);
INSERT INTO test.group_names (id, name, user_id) VALUES (140, 'клиенты', 35);
INSERT INTO test.group_names (id, name, user_id) VALUES (141, 'все контакты', 36);
INSERT INTO test.group_names (id, name, user_id) VALUES (142, 'друзья', 36);
INSERT INTO test.group_names (id, name, user_id) VALUES (143, 'знакомые', 36);
INSERT INTO test.group_names (id, name, user_id) VALUES (144, 'клиенты', 36);
INSERT INTO test.group_names (id, name, user_id) VALUES (145, 'все контакты', 37);
INSERT INTO test.group_names (id, name, user_id) VALUES (146, 'друзья', 37);
INSERT INTO test.group_names (id, name, user_id) VALUES (147, 'знакомые', 37);
INSERT INTO test.group_names (id, name, user_id) VALUES (148, 'клиенты', 37);
INSERT INTO test.group_names (id, name, user_id) VALUES (149, 'все контакты', 38);
INSERT INTO test.group_names (id, name, user_id) VALUES (150, 'друзья', 38);
INSERT INTO test.group_names (id, name, user_id) VALUES (151, 'знакомые', 38);
INSERT INTO test.group_names (id, name, user_id) VALUES (152, 'клиенты', 38);
INSERT INTO test.group_names (id, name, user_id) VALUES (153, 'все контакты', 39);
INSERT INTO test.group_names (id, name, user_id) VALUES (154, 'друзья', 39);
INSERT INTO test.group_names (id, name, user_id) VALUES (155, 'знакомые', 39);
INSERT INTO test.group_names (id, name, user_id) VALUES (156, 'клиенты', 39);
INSERT INTO test.group_names (id, name, user_id) VALUES (157, 'все контакты', 40);
INSERT INTO test.group_names (id, name, user_id) VALUES (158, 'друзья', 40);
INSERT INTO test.group_names (id, name, user_id) VALUES (159, 'знакомые', 40);
INSERT INTO test.group_names (id, name, user_id) VALUES (160, 'клиенты', 40);
INSERT INTO test.group_names (id, name, user_id) VALUES (161, 'все контакты', 41);
INSERT INTO test.group_names (id, name, user_id) VALUES (162, 'друзья', 41);
INSERT INTO test.group_names (id, name, user_id) VALUES (163, 'знакомые', 41);
INSERT INTO test.group_names (id, name, user_id) VALUES (164, 'клиенты', 41);
INSERT INTO test.group_names (id, name, user_id) VALUES (165, 'все контакты', 42);
INSERT INTO test.group_names (id, name, user_id) VALUES (166, 'друзья', 42);
INSERT INTO test.group_names (id, name, user_id) VALUES (167, 'знакомые', 42);
INSERT INTO test.group_names (id, name, user_id) VALUES (168, 'клиенты', 42);
INSERT INTO test.group_names (id, name, user_id) VALUES (169, 'все контакты', 43);
INSERT INTO test.group_names (id, name, user_id) VALUES (170, 'друзья', 43);
INSERT INTO test.group_names (id, name, user_id) VALUES (171, 'знакомые', 43);
INSERT INTO test.group_names (id, name, user_id) VALUES (172, 'клиенты', 43);
INSERT INTO test.group_names (id, name, user_id) VALUES (173, 'все контакты', 44);
INSERT INTO test.group_names (id, name, user_id) VALUES (174, 'друзья', 44);
INSERT INTO test.group_names (id, name, user_id) VALUES (175, 'знакомые', 44);
INSERT INTO test.group_names (id, name, user_id) VALUES (176, 'клиенты', 44);
INSERT INTO test.group_names (id, name, user_id) VALUES (177, 'все контакты', 45);
INSERT INTO test.group_names (id, name, user_id) VALUES (178, 'друзья', 45);
INSERT INTO test.group_names (id, name, user_id) VALUES (179, 'знакомые', 45);
INSERT INTO test.group_names (id, name, user_id) VALUES (180, 'клиенты', 45);
INSERT INTO test.group_names (id, name, user_id) VALUES (181, 'все контакты', 46);
INSERT INTO test.group_names (id, name, user_id) VALUES (182, 'друзья', 46);
INSERT INTO test.group_names (id, name, user_id) VALUES (183, 'знакомые', 46);
INSERT INTO test.group_names (id, name, user_id) VALUES (184, 'клиенты', 46);
INSERT INTO test.group_names (id, name, user_id) VALUES (185, 'все контакты', 47);
INSERT INTO test.group_names (id, name, user_id) VALUES (186, 'друзья', 47);
INSERT INTO test.group_names (id, name, user_id) VALUES (187, 'знакомые', 47);
INSERT INTO test.group_names (id, name, user_id) VALUES (188, 'клиенты', 47);
INSERT INTO test.group_names (id, name, user_id) VALUES (189, 'все контакты', 48);
INSERT INTO test.group_names (id, name, user_id) VALUES (190, 'друзья', 48);
INSERT INTO test.group_names (id, name, user_id) VALUES (191, 'знакомые', 48);
INSERT INTO test.group_names (id, name, user_id) VALUES (192, 'клиенты', 48);
INSERT INTO test.group_names (id, name, user_id) VALUES (193, 'все контакты', 49);
INSERT INTO test.group_names (id, name, user_id) VALUES (194, 'друзья', 49);
INSERT INTO test.group_names (id, name, user_id) VALUES (195, 'знакомые', 49);
INSERT INTO test.group_names (id, name, user_id) VALUES (196, 'клиенты', 49);
INSERT INTO test.group_names (id, name, user_id) VALUES (197, 'все контакты', 50);
INSERT INTO test.group_names (id, name, user_id) VALUES (198, 'друзья', 50);
INSERT INTO test.group_names (id, name, user_id) VALUES (199, 'знакомые', 50);
INSERT INTO test.group_names (id, name, user_id) VALUES (200, 'клиенты', 50);
INSERT INTO test.group_names (id, name, user_id) VALUES (201, 'все контакты', 51);
INSERT INTO test.group_names (id, name, user_id) VALUES (202, 'друзья', 51);
INSERT INTO test.group_names (id, name, user_id) VALUES (203, 'знакомые', 51);
INSERT INTO test.group_names (id, name, user_id) VALUES (204, 'клиенты', 51);
INSERT INTO test.group_names (id, name, user_id) VALUES (205, 'все контакты', 52);
INSERT INTO test.group_names (id, name, user_id) VALUES (206, 'друзья', 52);
INSERT INTO test.group_names (id, name, user_id) VALUES (207, 'знакомые', 52);
INSERT INTO test.group_names (id, name, user_id) VALUES (208, 'клиенты', 52);
INSERT INTO test.group_names (id, name, user_id) VALUES (209, 'все контакты', 53);
INSERT INTO test.group_names (id, name, user_id) VALUES (210, 'друзья', 53);
INSERT INTO test.group_names (id, name, user_id) VALUES (211, 'знакомые', 53);
INSERT INTO test.group_names (id, name, user_id) VALUES (212, 'клиенты', 53);
INSERT INTO test.group_names (id, name, user_id) VALUES (213, 'все контакты', 54);
INSERT INTO test.group_names (id, name, user_id) VALUES (214, 'друзья', 54);
INSERT INTO test.group_names (id, name, user_id) VALUES (215, 'знакомые', 54);
INSERT INTO test.group_names (id, name, user_id) VALUES (216, 'клиенты', 54);
INSERT INTO test.group_names (id, name, user_id) VALUES (217, 'все контакты', 55);
INSERT INTO test.group_names (id, name, user_id) VALUES (218, 'друзья', 55);
INSERT INTO test.group_names (id, name, user_id) VALUES (219, 'знакомые', 55);
INSERT INTO test.group_names (id, name, user_id) VALUES (220, 'клиенты', 55);
INSERT INTO test.group_names (id, name, user_id) VALUES (221, 'все контакты', 56);
INSERT INTO test.group_names (id, name, user_id) VALUES (222, 'друзья', 56);
INSERT INTO test.group_names (id, name, user_id) VALUES (223, 'знакомые', 56);
INSERT INTO test.group_names (id, name, user_id) VALUES (224, 'клиенты', 56);
INSERT INTO test.group_names (id, name, user_id) VALUES (225, 'все контакты', 57);
INSERT INTO test.group_names (id, name, user_id) VALUES (226, 'друзья', 57);
INSERT INTO test.group_names (id, name, user_id) VALUES (227, 'знакомые', 57);
INSERT INTO test.group_names (id, name, user_id) VALUES (228, 'клиенты', 57);
INSERT INTO test.group_names (id, name, user_id) VALUES (229, 'все контакты', 58);
INSERT INTO test.group_names (id, name, user_id) VALUES (230, 'друзья', 58);
INSERT INTO test.group_names (id, name, user_id) VALUES (231, 'знакомые', 58);
INSERT INTO test.group_names (id, name, user_id) VALUES (232, 'клиенты', 58);
INSERT INTO test.group_names (id, name, user_id) VALUES (233, 'все контакты', 59);
INSERT INTO test.group_names (id, name, user_id) VALUES (234, 'друзья', 59);
INSERT INTO test.group_names (id, name, user_id) VALUES (235, 'знакомые', 59);
INSERT INTO test.group_names (id, name, user_id) VALUES (236, 'клиенты', 59);
INSERT INTO test.group_names (id, name, user_id) VALUES (237, 'все контакты', 60);
INSERT INTO test.group_names (id, name, user_id) VALUES (238, 'друзья', 60);
INSERT INTO test.group_names (id, name, user_id) VALUES (239, 'знакомые', 60);
INSERT INTO test.group_names (id, name, user_id) VALUES (240, 'клиенты', 60);
INSERT INTO test.group_names (id, name, user_id) VALUES (241, 'все контакты', 61);
INSERT INTO test.group_names (id, name, user_id) VALUES (242, 'друзья', 61);
INSERT INTO test.group_names (id, name, user_id) VALUES (243, 'знакомые', 61);
INSERT INTO test.group_names (id, name, user_id) VALUES (244, 'клиенты', 61);
INSERT INTO test.group_names (id, name, user_id) VALUES (245, 'все контакты', 62);
INSERT INTO test.group_names (id, name, user_id) VALUES (246, 'друзья', 62);
INSERT INTO test.group_names (id, name, user_id) VALUES (247, 'знакомые', 62);
INSERT INTO test.group_names (id, name, user_id) VALUES (248, 'клиенты', 62);
INSERT INTO test.group_names (id, name, user_id) VALUES (249, 'все контакты', 63);
INSERT INTO test.group_names (id, name, user_id) VALUES (250, 'друзья', 63);
INSERT INTO test.group_names (id, name, user_id) VALUES (251, 'знакомые', 63);
INSERT INTO test.group_names (id, name, user_id) VALUES (252, 'клиенты', 63);
INSERT INTO test.group_names (id, name, user_id) VALUES (253, 'все контакты', 64);
INSERT INTO test.group_names (id, name, user_id) VALUES (254, 'друзья', 64);
INSERT INTO test.group_names (id, name, user_id) VALUES (255, 'знакомые', 64);
INSERT INTO test.group_names (id, name, user_id) VALUES (256, 'клиенты', 64);
INSERT INTO test.group_names (id, name, user_id) VALUES (257, 'все контакты', 65);
INSERT INTO test.group_names (id, name, user_id) VALUES (258, 'друзья', 65);
INSERT INTO test.group_names (id, name, user_id) VALUES (259, 'знакомые', 65);
INSERT INTO test.group_names (id, name, user_id) VALUES (260, 'клиенты', 65);
INSERT INTO test.group_names (id, name, user_id) VALUES (261, 'все контакты', 66);
INSERT INTO test.group_names (id, name, user_id) VALUES (262, 'друзья', 66);
INSERT INTO test.group_names (id, name, user_id) VALUES (263, 'знакомые', 66);
INSERT INTO test.group_names (id, name, user_id) VALUES (264, 'клиенты', 66);
INSERT INTO test.group_names (id, name, user_id) VALUES (265, 'все контакты', 67);
INSERT INTO test.group_names (id, name, user_id) VALUES (266, 'друзья', 67);
INSERT INTO test.group_names (id, name, user_id) VALUES (267, 'знакомые', 67);
INSERT INTO test.group_names (id, name, user_id) VALUES (268, 'клиенты', 67);
INSERT INTO test.group_names (id, name, user_id) VALUES (269, 'все контакты', 68);
INSERT INTO test.group_names (id, name, user_id) VALUES (270, 'друзья', 68);
INSERT INTO test.group_names (id, name, user_id) VALUES (271, 'знакомые', 68);
INSERT INTO test.group_names (id, name, user_id) VALUES (272, 'клиенты', 68);
INSERT INTO test.group_names (id, name, user_id) VALUES (273, 'все контакты', 69);
INSERT INTO test.group_names (id, name, user_id) VALUES (274, 'друзья', 69);
INSERT INTO test.group_names (id, name, user_id) VALUES (275, 'знакомые', 69);
INSERT INTO test.group_names (id, name, user_id) VALUES (276, 'клиенты', 69);
INSERT INTO test.group_names (id, name, user_id) VALUES (277, 'все контакты', 70);
INSERT INTO test.group_names (id, name, user_id) VALUES (278, 'друзья', 70);
INSERT INTO test.group_names (id, name, user_id) VALUES (279, 'знакомые', 70);
INSERT INTO test.group_names (id, name, user_id) VALUES (280, 'клиенты', 70);
INSERT INTO test.group_names (id, name, user_id) VALUES (281, 'все контакты', 71);
INSERT INTO test.group_names (id, name, user_id) VALUES (282, 'друзья', 71);
INSERT INTO test.group_names (id, name, user_id) VALUES (283, 'знакомые', 71);
INSERT INTO test.group_names (id, name, user_id) VALUES (284, 'клиенты', 71);
INSERT INTO test.group_names (id, name, user_id) VALUES (285, 'все контакты', 72);
INSERT INTO test.group_names (id, name, user_id) VALUES (286, 'друзья', 72);
INSERT INTO test.group_names (id, name, user_id) VALUES (287, 'знакомые', 72);
INSERT INTO test.group_names (id, name, user_id) VALUES (288, 'клиенты', 72);
INSERT INTO test.group_names (id, name, user_id) VALUES (289, 'все контакты', 73);
INSERT INTO test.group_names (id, name, user_id) VALUES (290, 'друзья', 73);
INSERT INTO test.group_names (id, name, user_id) VALUES (291, 'знакомые', 73);
INSERT INTO test.group_names (id, name, user_id) VALUES (292, 'клиенты', 73);
INSERT INTO test.group_names (id, name, user_id) VALUES (293, 'все контакты', 74);
INSERT INTO test.group_names (id, name, user_id) VALUES (294, 'друзья', 74);
INSERT INTO test.group_names (id, name, user_id) VALUES (295, 'знакомые', 74);
INSERT INTO test.group_names (id, name, user_id) VALUES (296, 'клиенты', 74);
INSERT INTO test.group_names (id, name, user_id) VALUES (297, 'все контакты', 75);
INSERT INTO test.group_names (id, name, user_id) VALUES (298, 'друзья', 75);
INSERT INTO test.group_names (id, name, user_id) VALUES (299, 'знакомые', 75);
INSERT INTO test.group_names (id, name, user_id) VALUES (300, 'клиенты', 75);
INSERT INTO test.group_names (id, name, user_id) VALUES (301, 'все контакты', 76);
INSERT INTO test.group_names (id, name, user_id) VALUES (302, 'друзья', 76);
INSERT INTO test.group_names (id, name, user_id) VALUES (303, 'знакомые', 76);
INSERT INTO test.group_names (id, name, user_id) VALUES (304, 'клиенты', 76);
INSERT INTO test.group_names (id, name, user_id) VALUES (305, 'все контакты', 77);
INSERT INTO test.group_names (id, name, user_id) VALUES (306, 'друзья', 77);
INSERT INTO test.group_names (id, name, user_id) VALUES (307, 'знакомые', 77);
INSERT INTO test.group_names (id, name, user_id) VALUES (308, 'клиенты', 77);
INSERT INTO test.group_names (id, name, user_id) VALUES (309, 'все контакты', 78);
INSERT INTO test.group_names (id, name, user_id) VALUES (310, 'друзья', 78);
INSERT INTO test.group_names (id, name, user_id) VALUES (311, 'знакомые', 78);
INSERT INTO test.group_names (id, name, user_id) VALUES (312, 'клиенты', 78);
INSERT INTO test.group_names (id, name, user_id) VALUES (313, 'все контакты', 79);
INSERT INTO test.group_names (id, name, user_id) VALUES (314, 'друзья', 79);
INSERT INTO test.group_names (id, name, user_id) VALUES (315, 'знакомые', 79);
INSERT INTO test.group_names (id, name, user_id) VALUES (316, 'клиенты', 79);
INSERT INTO test.group_names (id, name, user_id) VALUES (317, 'все контакты', 80);
INSERT INTO test.group_names (id, name, user_id) VALUES (318, 'друзья', 80);
INSERT INTO test.group_names (id, name, user_id) VALUES (319, 'знакомые', 80);
INSERT INTO test.group_names (id, name, user_id) VALUES (320, 'клиенты', 80);
INSERT INTO test.group_names (id, name, user_id) VALUES (321, 'все контакты', 81);
INSERT INTO test.group_names (id, name, user_id) VALUES (322, 'друзья', 81);
INSERT INTO test.group_names (id, name, user_id) VALUES (323, 'знакомые', 81);
INSERT INTO test.group_names (id, name, user_id) VALUES (324, 'клиенты', 81);
INSERT INTO test.group_names (id, name, user_id) VALUES (325, 'все контакты', 82);
INSERT INTO test.group_names (id, name, user_id) VALUES (326, 'друзья', 82);
INSERT INTO test.group_names (id, name, user_id) VALUES (327, 'знакомые', 82);
INSERT INTO test.group_names (id, name, user_id) VALUES (328, 'клиенты', 82);
INSERT INTO test.group_names (id, name, user_id) VALUES (329, 'все контакты', 83);
INSERT INTO test.group_names (id, name, user_id) VALUES (330, 'друзья', 83);
INSERT INTO test.group_names (id, name, user_id) VALUES (331, 'знакомые', 83);
INSERT INTO test.group_names (id, name, user_id) VALUES (332, 'клиенты', 83);
INSERT INTO test.group_names (id, name, user_id) VALUES (333, 'все контакты', 84);
INSERT INTO test.group_names (id, name, user_id) VALUES (334, 'друзья', 84);
INSERT INTO test.group_names (id, name, user_id) VALUES (335, 'знакомые', 84);
INSERT INTO test.group_names (id, name, user_id) VALUES (336, 'клиенты', 84);
INSERT INTO test.group_names (id, name, user_id) VALUES (337, 'все контакты', 85);
INSERT INTO test.group_names (id, name, user_id) VALUES (338, 'друзья', 85);
INSERT INTO test.group_names (id, name, user_id) VALUES (339, 'знакомые', 85);
INSERT INTO test.group_names (id, name, user_id) VALUES (340, 'клиенты', 85);
INSERT INTO test.group_names (id, name, user_id) VALUES (341, 'все контакты', 86);
INSERT INTO test.group_names (id, name, user_id) VALUES (342, 'друзья', 86);
INSERT INTO test.group_names (id, name, user_id) VALUES (343, 'знакомые', 86);
INSERT INTO test.group_names (id, name, user_id) VALUES (344, 'клиенты', 86);
INSERT INTO test.group_names (id, name, user_id) VALUES (345, 'все контакты', 87);
INSERT INTO test.group_names (id, name, user_id) VALUES (346, 'друзья', 87);
INSERT INTO test.group_names (id, name, user_id) VALUES (347, 'знакомые', 87);
INSERT INTO test.group_names (id, name, user_id) VALUES (348, 'клиенты', 87);
INSERT INTO test.group_names (id, name, user_id) VALUES (349, 'все контакты', 88);
INSERT INTO test.group_names (id, name, user_id) VALUES (350, 'друзья', 88);
INSERT INTO test.group_names (id, name, user_id) VALUES (351, 'знакомые', 88);
INSERT INTO test.group_names (id, name, user_id) VALUES (352, 'клиенты', 88);
INSERT INTO test.group_names (id, name, user_id) VALUES (353, 'все контакты', 89);
INSERT INTO test.group_names (id, name, user_id) VALUES (354, 'друзья', 89);
INSERT INTO test.group_names (id, name, user_id) VALUES (355, 'знакомые', 89);
INSERT INTO test.group_names (id, name, user_id) VALUES (356, 'клиенты', 89);
INSERT INTO test.group_names (id, name, user_id) VALUES (357, 'все контакты', 90);
INSERT INTO test.group_names (id, name, user_id) VALUES (358, 'друзья', 90);
INSERT INTO test.group_names (id, name, user_id) VALUES (359, 'знакомые', 90);
INSERT INTO test.group_names (id, name, user_id) VALUES (360, 'клиенты', 90);
INSERT INTO test.group_names (id, name, user_id) VALUES (361, 'все контакты', 91);
INSERT INTO test.group_names (id, name, user_id) VALUES (362, 'друзья', 91);
INSERT INTO test.group_names (id, name, user_id) VALUES (363, 'знакомые', 91);
INSERT INTO test.group_names (id, name, user_id) VALUES (364, 'клиенты', 91);
INSERT INTO test.group_names (id, name, user_id) VALUES (365, 'все контакты', 92);
INSERT INTO test.group_names (id, name, user_id) VALUES (366, 'друзья', 92);
INSERT INTO test.group_names (id, name, user_id) VALUES (367, 'знакомые', 92);
INSERT INTO test.group_names (id, name, user_id) VALUES (368, 'клиенты', 92);
INSERT INTO test.group_names (id, name, user_id) VALUES (369, 'все контакты', 93);
INSERT INTO test.group_names (id, name, user_id) VALUES (370, 'друзья', 93);
INSERT INTO test.group_names (id, name, user_id) VALUES (371, 'знакомые', 93);
INSERT INTO test.group_names (id, name, user_id) VALUES (372, 'клиенты', 93);
INSERT INTO test.group_names (id, name, user_id) VALUES (373, 'все контакты', 94);
INSERT INTO test.group_names (id, name, user_id) VALUES (374, 'друзья', 94);
INSERT INTO test.group_names (id, name, user_id) VALUES (375, 'знакомые', 94);
INSERT INTO test.group_names (id, name, user_id) VALUES (376, 'клиенты', 94);
INSERT INTO test.group_names (id, name, user_id) VALUES (377, 'все контакты', 95);
INSERT INTO test.group_names (id, name, user_id) VALUES (378, 'друзья', 95);
INSERT INTO test.group_names (id, name, user_id) VALUES (379, 'знакомые', 95);
INSERT INTO test.group_names (id, name, user_id) VALUES (380, 'клиенты', 95);
INSERT INTO test.group_names (id, name, user_id) VALUES (381, 'все контакты', 96);
INSERT INTO test.group_names (id, name, user_id) VALUES (382, 'друзья', 96);
INSERT INTO test.group_names (id, name, user_id) VALUES (383, 'знакомые', 96);
INSERT INTO test.group_names (id, name, user_id) VALUES (384, 'клиенты', 96);
INSERT INTO test.group_names (id, name, user_id) VALUES (385, 'все контакты', 97);
INSERT INTO test.group_names (id, name, user_id) VALUES (386, 'друзья', 97);
INSERT INTO test.group_names (id, name, user_id) VALUES (387, 'знакомые', 97);
INSERT INTO test.group_names (id, name, user_id) VALUES (388, 'клиенты', 97);
INSERT INTO test.group_names (id, name, user_id) VALUES (389, 'все контакты', 98);
INSERT INTO test.group_names (id, name, user_id) VALUES (390, 'друзья', 98);
INSERT INTO test.group_names (id, name, user_id) VALUES (391, 'знакомые', 98);
INSERT INTO test.group_names (id, name, user_id) VALUES (392, 'клиенты', 98);
INSERT INTO test.group_names (id, name, user_id) VALUES (393, 'все контакты', 99);
INSERT INTO test.group_names (id, name, user_id) VALUES (394, 'друзья', 99);
INSERT INTO test.group_names (id, name, user_id) VALUES (395, 'знакомые', 99);
INSERT INTO test.group_names (id, name, user_id) VALUES (396, 'клиенты', 99);
INSERT INTO test.group_names (id, name, user_id) VALUES (397, 'все контакты', 100);
INSERT INTO test.group_names (id, name, user_id) VALUES (398, 'друзья', 100);
INSERT INTO test.group_names (id, name, user_id) VALUES (399, 'знакомые', 100);
INSERT INTO test.group_names (id, name, user_id) VALUES (400, 'клиенты', 100);